export const GET_CUSTOMERS_REQUEST = "CUSTOMERS.GET_CUSTOMERS_REQUEST";
export const GET_CUSTOMERS_SUCCESS = "CUSTOMERS.GET_CUSTOMERS_SUCCESS";
export const GET_CUSTOMERS_FAILURE = "CUSTOMERS.GET_CUSTOMERS_FAILURE";

export const CREATE_CUSTOMERS_REQUEST = "CUSTOMERS.CREATE_CUSTOMERS_REQUEST";
export const CREATE_CUSTOMERS_SUCCESS = "CUSTOMERS.CREATE_CUSTOMERS_SUCCESS";
export const CREATE_CUSTOMERS_FAILURE = "CUSTOMERS.CREATE_CUSTOMERS_FAILURE";
